# Figures for the logit simulation result in DGP_logit_simulation.R

# Set working directory to current source file location first.

#setwd(dirname(rstudioapi::getActiveDocumentContext()$path)) # if you are using RStudio
setwd("/<PATH>/<TO>/<SOURCE>/<FILE>/")

# read the simulation data generated by "DGP_logit_simulation.R"
final_out <- readRDS(file = "../02_experiment/experiment/sim_res/DGP_sim_logit_result.rds")

# fix index
sim_out <- final_out[[1]]
design_table <- final_out[[2]]
total_sim_size <- length(final_out[[1]])

length(final_out[[1]])/nrow(design_table)
design_table

{
  ind <- unlist(sapply(seq(1:total_sim_size), function(x) sim_out[[x]][[1]]))
  
  # Main 
  res_Pro <- do.call("rbind", lapply(seq(1:total_sim_size),
                                     FUN = function(x) sim_out[[x]][[2]]))
  
  res_dm <- do.call("rbind", lapply(seq(1:total_sim_size),
                                    FUN = function(x) sim_out[[x]][[3]]))
  
  # TRUE
  true <- do.call("rbind", lapply(seq(1:total_sim_size),
                                  FUN = function(x) sim_out[[x]][[4]]))
}

## lm 
ncol_X <- dim(res_dm)[2]/2

compare_lm_dm <- matrix(NA, nrow = nrow(design_table), ncol = ncol_X)
compare_lm_Pro <- matrix(NA, nrow = nrow(design_table), ncol = ncol_X)
compare_lm_dm_ci <- matrix(NA, nrow = nrow(design_table), ncol = ncol_X)
compare_lm_Pro_ci <- matrix(NA, nrow = nrow(design_table), ncol = ncol_X)
compare_lm_dm_sd <- matrix(NA, nrow = nrow(design_table), ncol = ncol_X)
compare_lm_Pro_sd <- matrix(NA, nrow = nrow(design_table), ncol = ncol_X)
true_coef_mat <- matrix(NA, nrow = nrow(design_table), ncol = ncol_X)

for(i in 1:nrow(design_table)){
  
  # TRUE_coef
  true_coef_mat[i, 1:ncol_X] <- true_coef <- apply(true[ind == i, 1:ncol_X], 2, mean)
  
  # SO
  compare_lm_Pro[i, 1:ncol_X] <- apply(res_Pro[ind == i, 1:ncol_X], 2, mean) - true_coef
  ci_low <- apply(res_Pro[ind == i, 1:ncol_X] - 1.96*res_Pro[ind == i, ncol_X + (1:ncol_X)], 1, 
                  function(x) x <= true_coef)
  ci_high <- apply(res_Pro[ind == i, 1:ncol_X] + 1.96*res_Pro[ind == i, ncol_X + (1:ncol_X)], 1, 
                   function(x) x >= true_coef)
  compare_lm_Pro_ci[i, 1:ncol_X] <- apply(ci_low*ci_high, 1, mean)
  compare_lm_Pro_sd[i, 1:ncol_X] <- apply(res_Pro[ind == i, 1:ncol_X], 2, sd)
  
  # DSL
  compare_lm_dm[i, 1:ncol_X] <- apply(res_dm[ind == i, 1:ncol_X], 2, mean) - true_coef
  ci_low <- apply(res_dm[ind == i, 1:ncol_X] - 1.96*res_dm[ind == i, ncol_X + (1:ncol_X)], 1, 
                  function(x) x <= true_coef)
  ci_high <- apply(res_dm[ind == i, 1:ncol_X] + 1.96*res_dm[ind == i, ncol_X + (1:ncol_X)], 1, 
                   function(x) x >= true_coef)
  compare_lm_dm_ci[i, 1:ncol_X] <- apply(ci_low*ci_high, 1, mean)
  compare_lm_dm_sd[i, 1:ncol_X] <- apply(res_dm[ind == i, 1:ncol_X], 2, sd)
}

# standardize
true_coef_base <- apply(true_coef_mat, 1, function(x) sqrt(mean(x^2)))

# RMSE
RMSE_Pro <- apply(sqrt(compare_lm_Pro_sd^2 + compare_lm_Pro^2), 1, mean)
RMSE_dm <- apply(sqrt(compare_lm_dm_sd^2 + compare_lm_dm^2), 1, mean)

# Bias Figure 
PO_b  <- apply(compare_lm_Pro, 1, function(x) sqrt(mean(x^2)))/true_coef_base
dsl_b <- apply(compare_lm_dm, 1, function(x) sqrt(mean(x^2)))/true_coef_base
# Coverage 
PO_ci  <- apply(compare_lm_Pro_ci, 1, mean)
dsl_ci <- apply(compare_lm_dm_ci, 1, mean)
# Coverage 
PO_ci  <- apply(compare_lm_Pro_ci, 1, mean)
dsl_ci <- apply(compare_lm_dm_ci, 1, mean)
# RMSE
PO_RMSE  <- RMSE_Pro
dsl_RMSE <- RMSE_dm

design_table
use_index <- c(1:6)
x_use <- design_table$prob_prox[use_index]

if (!dir.exists("figure")) {
  dir.create("figure")
} 

pdf("figure/Figure.1a_sim_main.pdf", height = 2.5, width = 9)
par(mfrow = c(1,3), mar = c(4.5, 4.5, 4, 2))
plot(x_use, PO_b[use_index], ylim = c(0, 1),
     ylab = "Standardized Bias", xlab = "Accuracy of LLMs", 
     xaxt='n', main = "Bias", pch = 19, col = "red", type = "b", lwd = 2,
     cex.axis = 1.25, cex.lab= 1.5, cex.main = 1.75)
Axis(side = 1, at = x_use, labels = x_use, cex.axis = 1.25)
points(x_use, dsl_b[use_index], pch = 15, col = "blue", type = "b", lwd = 2)
abline(h = 0, lty = 2, lwd = 2)
legend("topright", legend = c("SO", "DSL"),
       pch = c(19, 15), col = c("red", "blue"), lwd = 2)

plot(x_use, PO_ci[use_index], ylim = c(0, 1),
     ylab = "Coverage Percentage", xlab = "Accuracy of LLMs", 
     xaxt='n', main = "Coverage", pch = 19, col = "red", type = "b", lwd = 2,
     cex.axis = 1.25, cex.lab= 1.5, cex.main = 1.75)
Axis(side = 1, at = x_use, labels = x_use, cex.axis = 1.25)
points(x_use, dsl_ci[use_index], pch = 15, col = "blue", type = "b", lwd = 2)
abline(h = 0.95, lty = 2, lwd = 2)

plot(x_use, log(PO_RMSE[use_index]), ylim = c(-3, -1),
     ylab = "RMSE", xlab = "Accuracy of LLMs", 
     xaxt='n', main = "RMSE", pch = 19, col = "red", type = "b", lwd = 2, yaxt = "n",
     cex.axis = 1.25, cex.lab= 1.5, cex.main = 1.75)
Axis(side = 1, at = x_use, labels = x_use, cex.axis = 1.25)
points(x_use, log(dsl_RMSE[use_index]), pch = 15, col = "blue", type = "b", lwd = 2)
Axis(side = 2, at = c(-3, -2.5, -2, -1.5, -1.0), 
     labels = round(exp(c(-3, -2.5, -2, -1.5, -1.0)), 2))
abline(h = 0.95, lty = 2, lwd = 2)
dev.off()
