#!/usr/bin/R
#
# Rejoining SLURM results
#
# Script for rejoining measure results, merging all single simulation rds files into a merged rds file and a merged csv.

# Set working directory to current source file location first.
#setwd(dirname(rstudioapi::getActiveDocumentContext()$path)) # if you are using RStudio
setwd("/<PATH>/<TO>/<SOURCE>/<FILE>/")

results_dir <- "<PATH>/<TO>/<REPO>/<OUT_FOLDER>/" # here is the script to process all measure datasets, this dir inlcudes all subfolders, each folder includes all simulation rds files for one input file. For example, "multi_discourse_pos_a" contains all simulation ids files that generated by using the file "multi_discourse_pos-a.csv" as input data.
source_dir <- "../01_data_and_preprocessing/measurement/binarized_datasets/"
out_dir <-"measurement_results/"

if (!dir.exists(out_dir)) {
  dir.create(out_dir)
} 

# Read in files
task_dirs <- list.dirs(results_dir)
# out_files <- list.files(results_dir) # Now nested
source_files <- list.files(source_dir)

# Step 1: Get task from source files
tasks <- unique(sapply(source_files, function(f){
  regmatches(f,  regexec("^(?:binary|multi)_(.*)_pos-.+\\.csv", f))[[1]][2]
}))

# Function
simulation_to_long_df <- function(task) {
  # Step 1 get tasks/dirs
  out_files <- list.files(task_dirs[grep(task, task_dirs)]) # For new directory structure
  task_datasets <- sapply(source_files, function(f) {
    regmatches(f,  regexec(paste0(
      "^((binary|multi)_",
      task,
      "_pos-.+)\\.csv"
    )
    , f))[[1]][2]
  })
  task_datasets <- task_datasets[!is.na(task_datasets)]
  
  # Step 2: Read in the corresponding RDS files into nested list haha
   raw_data <- lapply(task_datasets, function(td) {
     sapply(list.files(paste0(results_dir, gsub('-', '_', td))),
            function(ff){
              readRDS(paste0(results_dir, gsub('-', '_', td), '/', ff))})
   })
  
  
  # Step 3: Parse raw data into dataframe
  # We just need a custom parser here
  # Construct rows
  out <- list()
  i = 1
  for (src_file in names(raw_data)) {
    # The source file
    for (sim_file in names(raw_data[[src_file]])) {
      # The simulation
      # Horrific regex parsing
      # src_file <- names(raw_data)[1]
      # sim_file <- names(raw_data[[src_file]])[1]
      parsed <-   regmatches(
        sim_file,
        regexec(
          "^([0-9]{6}_[0-9]{4})_(binary|multi)_(.*)_pos-(.+)\\.csv_HPCversion_sim([0-9]+)_boot([0-9]+)_sim([0-9]+)\\.rds",
          sim_file
        )
      )[[1]]
      
      # Extract items
      date_time <- parsed[2]
      task_type <- parsed[3] # binary, multi
      task_name <- parsed[4] # e.g. media_ideology
      pos_class <- parsed[5] # e.g. a, b, c
      sim_size  <- parsed[6] # Number of simulations per design
      boot_iter <- parsed[7] # Number of bootstraps for SSL
      sim_num   <- parsed[8] # Simulation number
      
      # Extract values
      sim <- raw_data[[src_file]][[sim_file]]
      des_num <- sim[[1]]
      for (estim in names(sim)[-1]) {
        # Get point estimate
        param_name <- 'point'
        row <- c(
          date_time = date_time,
          des_num = des_num,
          task_type = task_type,
          task_name = task_name,
          pos_class = pos_class,
          sim_size = sim_size,
          boot_iter = boot_iter,
          sim_num = sim_num,
          estimator = estim,
          param_name = param_name,
          value = sim[[estim]][1]
        )
        out[[i]] <- row
        i = i + 1
        # Get se
        if (estim != 'true_lo') {
          param_name <- 'se'
          row <- c(
            date_time = date_time,
            des_num = des_num,
            task_type = task_type,
            task_name = task_name,
            pos_class = pos_class,
            sim_size = sim_size,
            boot_iter = boot_iter,
            sim_num = sim_num,
            estimator = estim,
            param_name = param_name,
            value = sim[[estim]][2]
          )
          out[[i]] <- row
          i = i + 1
        }
      }
    }
  }
  out_df <- data.frame(do.call(rbind, out))
  if (length(out_df)>1){
    write.csv(x = out_df, file = paste0(out_dir, task, '.csv'))
  }
  return(out_df)
}
  
# Run
for (task in tasks) {
  out_df <- simulation_to_long_df(task)
  print(c(task, nrow(out_df)))
}


