#!/usr/bin/R
# Rejoining SLURM results
# Script for rejoining results generated by slurm job

# Set working directory to current source file location first.
#setwd(dirname(rstudioapi::getActiveDocumentContext()$path)) # if you are using RStudio
setwd("/<PATH>/<TO>/<SOURCE>/<FILE>/")

# Set the simulation result folder
results_dir <-"<PATH>/<TO>/<REPO>/<OUT_FOLDER>/" 


# Add design
design <- expand.grid(
  "ss" = 15000,
  "read" = c(25, 50, 100, 150, 200),
  "prob_prox" = c("all", "openai", "hf", "best", "text-davinci-003","flan-ul2") #c("all", "openai", "hf", "best", "text-davinci-003")
) 

folder_names <- list.dirs(results_dir, recursive = FALSE)
folder_names <- basename(folder_names)

generate_rds <- function(rds_folder){
  dataset_result_dir <- paste0(results_dir, rds_folder, '/')
  
  # Read results
  out_files <- list.files(dataset_result_dir)
  out_order <-  sapply(out_files, function(f){
    as.numeric(regmatches(f,  regexec("sim([0-9]{4,5})\\.rds", f))[[1]][2])
  })
  out_files <- out_files[order(out_order)]
  sim_out <- sapply(out_files, function(x){readRDS(paste0(dataset_result_dir, x))})
  
  # Create final out file
  final_out <- list("sim_out" = sim_out, "design" = design)
  final_file <- gsub("_(sim)?[0-9]{4}", "", out_files[1]) # some ugly regex hacks
  saveRDS(final_out, final_file)
}


# generate rds file for each dataset experiment result folder
for (rds_folder in folder_names){
  generate_rds(rds_folder)
  }

